GET http://127.0.0.1:8000/health HTTP/1.1

###
POST http://localhost:8000/trade
Content-Type: application/json

{
    "symbol": "EURGBP",
    "direction": "SELL",
    "entry": {
      "price": 0.8437,
      "type": "limit",
      "validUntil": "2025-05-30T18:12:00.605+01:00"
    },
    "stopLoss": 0.8437,
    "takeProfits": [{
      "name":"TP1",
      "price":0.82165,
      "percentage":30,
      "reason":"TP1"
    } ],
    "confidence": 7,
    "reason": "Downtrend confirmed on 1H timeframe with bearish pin bar and engulfing pattern on 15M timeframe at resistance.",
    "timestamp": "2025-05-29T17:12:00.605+01:00"
  }